<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x86</PlatformTarget>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ConsoleRendererCheck\**" />
    <Compile Remove="Test\**" />
    <EmbeddedResource Remove="ConsoleRendererCheck\**" />
    <EmbeddedResource Remove="Test\**" />
    <None Remove="ConsoleRendererCheck\**" />
    <None Remove="Test\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Engine_.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AForge.Video.FFMPEG" Version="2.2.5.1-rc" />
    <PackageReference Include="MediaToolkit" Version="1.1.0.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.10" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
    <PackageReference Include="System.Runtime.WindowsRuntime.UI.Xaml" Version="4.7.0" />
    <PackageReference Include="System.Windows.Extensions" Version="8.0.0" />
  </ItemGroup>

</Project>
