<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ConsoleRendererCheck\**" />
    <Compile Remove="Test\**" />
    <EmbeddedResource Remove="ConsoleRendererCheck\**" />
    <EmbeddedResource Remove="Test\**" />
    <None Remove="ConsoleRendererCheck\**" />
    <None Remove="Test\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Lib\Legacy.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove=".gitignore" />
    <None Remove="ConsoleRenderer.drawio" />
    <None Remove="LICENSE" />
    <None Remove="README.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FFMediaToolkit" Version="4.8.1" />
    <PackageReference Include="FFmpeg.AutoGen" Version="7.1.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

</Project>
